version: '3'
services:

  discovery:
    image: test-micro-services-gft
    container_name: customer-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
      - "8888:8888"
      - "8080:8080"
      - "8091:8091"
      - "27017:27017"
